### ISSUE TITLE
need to deal with UDP

### ISSUE THREAD

**Issue by augre** [arthurcolle/drench-udp#1]
Hi,

I am trying to use drench the first time and getting this:
udp://tracker.coppersurfer.tk:6969/announce

Traceback (most recent call last):
  File "/software/python/2.7.6/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/python/2.7.6/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xrzheng/.local/lib/python2.7/site-packages/drench/__main__.py", line 3, in <module>
    main()
  File "/home/xrzheng/.local/lib/python2.7/site-packages/drench/drench.py", line 323, in main
    mytorrent.tracker_request()
  File "/home/xrzheng/.local/lib/python2.7/site-packages/drench/drench.py", line 186, in tracker_request
    raise Exception('need to deal with UDP')
Exception: need to deal with UDP

**Comment by augre** [comment]
Oh I see in the readme that udp doesn't work.
